name: proyecto_savory
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.15.2
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  flutter_svg: ^2.2.1
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.0
  firebase_storage: ^12.4.10
  google_sign_in: ^6.2.1
  google_generative_ai: ^0.4.7
  dio: ^5.9.0
  flutter_dotenv: ^5.2.1            
  image_picker: ^1.1.2            
  google_mlkit_text_recognition: ^0.13.1  
  permission_handler: ^11.3.1       
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/onboarding/
    - assets/
